var module;
if (module === undefined) {
  module = {};
}

// A wrapper around the autogenerated .js from emsciprten. 
class CalculatorWorker {
  constructor() {
    /**@type{Worker|null} */
    this.worker = null;
  }

  compute(
    /** @type{string} */
    input,
    /** @type{function} */
    callback
  ) {
    if (this.worker === null) {
      this.worker = new Worker("/calculator_html/web_assembly/calculator_web_assembly_all_in_one.js");
    }
    this.worker.postMessage(["compute", input]);
    this.worker.onmessage = (message) => {
      this.receiveResult(message.data, callback);
    }
  }

  receiveResult(
    /**@type {string} */
    data,
    /** @type{function} */
    callback,
  ) {
    callback(data);
  }
}

let calculatorWorker = new CalculatorWorker();

module.exports = {
  calculatorWorker,
};