var module;
if (module === undefined) {
  module = {};
}

// A wrapper around the autogenerated .js from emsciprten. 
class CalculatorWasm {
  constructor() {
    /**@type{string} */
    this.lastInput = "";
    this.flagInitializationStarted = false;
    this.ready = false;
    this.calculatorWasm = null;
  }
  getChar(tty) {
    if (tty.input.length !== 0) {
      return tty.input.shift();
    }
    tty.input = this.calculatorWasm.intArrayFromString(this.lastInput + "\n", true);
    return tty.input.shift();
  }

  callMain(
    /**@type {string} */
    input,
    /**@type {function} */
    callback,
  ) {
    this.lastInput = input;
    if (!this.flagInitializationStarted) {
      this.initialize(callback);
      return;
    }
    if (this.ready) {
      this.doCallCalculator(callback);
      return;
    }
    setTimeout(() => {
      this.callMain(input, callback);
    }, 1000);
  }

  initialize(callback) {
    if (this.flagInitializationStarted) {
      return;
    }
    this.flagInitializationStarted = true;

    // File name is relative to calculator_html folder.
    // Improtant: the file calculator.js
    // is autogenerated and kept in its pure autogenerated form.
    // It will have an extra "module.exports" code snippet appended to it 
    // by the calculator server during the browserification process.
    this.calculatorWasm = require("./web_assembly/calculator");
    this.calculatorWasm.TTY.default_tty_ops.get_char = (tty) => {
      this.getChar(tty);
    }
    this.calculatorWasm.addOnInit(() => {
      this.ready = true;
      this.doCallCalculator(callback);
    });
  }
  doCallCalculator(
    /**@type {function} */
    callback,
  ) {
    let result = this.calculatorWasm.Module.ccall('callCalculator', 'string', ['string'], [this.lastInput]);
    console.log(result);
    if (callback !== null && callback !== undefined) {
      callback(result);
    }
    this.calculatorWasm._free(result);
  }
}

let calculatorWasm = new CalculatorWasm();

module.exports = {
  calculatorWasm,
}