var module;
if (module === undefined) {
  module = {};
}

// A wrapper around the autogenerated .js from emsciprten. 
class CalculatorWebAssembly {
  constructor() {
    /**@type{string} */
    this.lastInput = "";
    this.flagInitializationStarted = false;
    this.ready = false;
    // Pointer to the web assembly module in ./web_assembly/calculator.js
    // Improtant: the file calculator.js
    // is autogenerated and kept in its pure autogenerated form.
    // It will have an extra "module.exports" code snippet appended to it 
    // by the calculator server during the browserification process.
    // Important: due to the way the autogenerated .js works as of writing, 
    // it auto-downloads the binary .wasm file. This is a heavy operation
    // and must only be done on-demand. Therefore, with the current state of
    // the autogenerated bootstrap code, please keep the web assembly import here.
    this.calculatorWebAssembly = null;
  }

  getChar(tty) {
    if (tty.input.length !== 0) {
      return tty.input.shift();
    }
    tty.input = this.calculatorWebAssembly.intArrayFromString(this.lastInput + "\n", true);
    return tty.input.shift();
  }

  callMain(
    /**@type {string} */
    input,
    /**@type {function} */
    callback,
  ) {
    this.lastInput = input;
    if (!this.flagInitializationStarted) {
      this.initialize(callback);
      return;
    }
    if (this.ready) {
      this.doCallCalculator(callback);
      return;
    }
    setTimeout(() => {
      this.callMain(input, callback);
    }, 1000);
  }

  initialize(callback) {
    if (this.flagInitializationStarted) {
      return;
    }
    this.flagInitializationStarted = true;

    // File name is relative to calculator_html folder.
    this.calculatorWebAssembly = require("./web_assembly/calculator");
    this.calculatorWebAssembly.TTY.default_tty_ops.get_char = (tty) => {
      this.getChar(tty);
    }
    this.calculatorWebAssembly.addOnInit(() => {
      this.ready = true;
      this.doCallCalculator(callback);
    });
  }

  doCallCalculator(
    /**@type {function} */
    callback,
  ) {
    let result = this.calculatorWebAssembly.Module.ccall('callCalculator', 'string', ['string'], [this.lastInput]);
    console.log(result);
    if (callback !== null && callback !== undefined) {
      callback(result);
    }
    this.calculatorWebAssembly._free(result);
  }
}

let calculatorWebAssembly = new CalculatorWebAssembly();

module.exports = {
  calculatorWebAssembly,
}