var module;
if (module === undefined) {
  module = {};
}

// A wrapper around the autogenerated .js from emsciprten. 
class CalculatorWorker {
  constructor() {
    /**@type{Worker|null} */
    this.worker = null;
  }

  compute(
    /** @type{string} */
    input,
    /** @type{function} */
    callback
  ) {
    console.log("DEBUG: Got input " + input);
    this.worker = new Worker("/calculator_html/javascript_all_in_one.js");
    this.worker.postMessage("DEBUG: hello world!");
  }

  receiveResult(
    /**@type {string} */
    data,
    /** @type{function} */
    callback,
  ) {
    console.log("DEBUG: Received from worker: " + data);
    callback(data);
  }
}

let calculatorWorker = new CalculatorWorker();

module.exports = {
  calculatorWorker,
};