var module;
if (module === undefined) {
  module = {};
}

// A wrapper around the autogenerated .js from emsciprten. 
class CalculatorWasm {
  constructor() {
    /**@type{string} */
    this.lastInput = "";
    this.flagInitialized = false;
    this.calculatorWasm = null;
  }
  getChar(tty) {
    if (tty.input.length !== 0) {
      return tty.input.shift();
    }
    tty.input = this.calculatorWasm.intArrayFromString(this.lastInput + "\n", true);
    return tty.input.shift();
  }

  callMain(
    /**@type {string} */
    input,
  ) {
    this.lastInput = input;
    this.initialize();
    setTimeout(() => {
      this.calculatorWasm.Module.ccall('callCalculator', 'number', ['string'], [input]);
    }, 3000);
  }

  initialize() {
    if (this.flagInitialized) {
      return;
    }
    // File name is relative to calculator-html folder.
    // Improtant: the file calculator.js
    // is autogenerated and kept in its pure autogenerated form.
    // It will have an extra "module.exports" code snippet appended to it 
    // by the calculator server during the browserification process.
    this.calculatorWasm = require("./web_assembly/calculator");
    this.calculatorWasm.TTY.default_tty_ops.get_char = (tty) => {
      this.getChar(tty);
    }
  }
}

let calculatorWasm = new CalculatorWasm();

module.exports = {
  calculatorWasm,
}