QT+=core
QT-=gui
TARGET=calculator
CONFIG+=console
CONFIG-=app_bundle
CONFIG+=c++11
QMAKE_CXXFLAGS+=-std=c++11

TEMPLATE=app

DEFINES+=MACRO_use_open_ssl
DEFINES+=MACRO_use_MongoDB

LIBS+=-lmongoc-1.0
LIBS+=-lbson-1.0

# LIBS+=-lssl
# LIBS+=-lcrypto

INCLUDEPATH+=/usr/local/include/libmongoc-1.0
INCLUDEPATH+=/usr/local/include/libbson-1.0

HEADERS += \
    source_code_formatter.h \
    string_constants.h \
    vpf.h \
    vpfFiniteFields.h \
    vpfHeader1General0_General.h \
    vpfHeader1General1_ListReferences.h \
    vpfHeader1General2Multitasking.h \
    vpfHeader1General3_Test.h \
    vpfHeader1General4General_Logging_GlobalVariables.h \
    vpfHeader1General5TimeDate.h \
    vpfHeader1General6Maps.h \
    vpfHeader1General7FileOperations_Encodings.h \
    vpfHeader1General8DatabaseSystemIndependent.h \
    vpfHeader2Math01_LargeIntArithmetic.h \
    vpfHeader2Math02_Vectors.h \
    vpfHeader2Math0_General.h \
    vpfHeader2Math10_LaTeXRoutines.h \
    vpfHeader2Math11_EllipticCurves.h \
    vpfHeader2Math15_UniversalEnveloping.h \
    vpfHeader2Math1_2SemisimpleLieAlgebras_RootSubalgebras.h \
    vpfHeader2Math1_3SemisimpleLieSubalgebras.h \
    vpfHeader2Math1_LieTheoryExtras.h \
    vpfHeader2Math1_SemisimpleLieAlgebras.h \
    vpfHeader2Math2_AlgebraicNumbers.h \
    vpfHeader2Math3_FiniteGroups.h \
    vpfHeader2Math3_SymmetricGroupsAndGeneralizations.h \
    vpfHeader2Math4_5_Tree.h \
    vpfHeader2Math4_Graph.h \
    vpfHeader2Math5_SubsetsSelections.h \
    vpfHeader2Math6_ModulesSSLieAlgebras.h \
    vpfHeader2Math7_PackedVector.h \
    vpfHeader2Math8_VectorSpace.h \
    vpfHeader2Math9DrawingVariables.h \
    vpfHeader3Calculator0_Interface.h \
    vpfHeader3Calculator1_InnerTypedFunctions.h \
    vpfHeader3Calculator2_InnerFunctions.h \
    vpfHeader3Calculator3_WeylGroupCharacters.h \
    vpfHeader3Calculator4HtmlFunctions.h \
    vpfHeader3Calculator5_Database_Mongo.h \
    vpfHeader4SystemFunctionsGlobalObjects.h \
    vpfHeader5Crypto.h \
    vpfHeader6WebServerInterprocessLogistics.h \
    vpfHeader7DatabaseInterface.h \
    vpfHeader7DatabaseInterface_Mongodb.h \
    vpfHeader8HtmlInterpretation.h \
    vpfHeader8HtmlInterpretationInterface.h \
    vpfHeader8HtmlSnippets.h \
    vpfImplementationHeader2Math051_PolynomialComputations_Basic.h \
    vpfImplementationHeader2Math052_PolynomialComputations_Advanced.h \
    vpfImplementationHeader2Math0_General.h \
    vpfImplementationHeader2Math11_EllipticCurves.h \
    vpfImplementationHeader2Math15_UniversalEnveloping.h \
    vpfImplementationHeader2Math1_SemisimpleLieAlgebras.h \
    vpfImplementationHeader2Math3_FiniteGroups.h \
    vpfImplementationHeader2Math3_WeylAlgebra.h \
    vpfImplementationHeader2Math6_ModulesSSLieAlgebras.h \
    vpfImplementationHeader2Math7_PackedVector.h \
    vpfJson.h \
    vpfMacros.h \
    vpfPackedVector.h \
    webserver.h \
    openssl/crypto/aes/aes_locl.h \
    openssl/crypto/asn1/asn1_item_list.h \
    openssl/crypto/asn1/asn1_locl.h \
    openssl/crypto/asn1/charmap.h \
    openssl/crypto/asn1/standard_methods.h \
    openssl/crypto/asn1/tbl_standard.h \
    openssl/crypto/async/arch/async_null.h \
    openssl/crypto/async/arch/async_posix.h \
    openssl/crypto/async/arch/async_win.h \
    openssl/crypto/async/async_locl.h \
    openssl/crypto/bf/bf_locl.h \
    openssl/crypto/bf/bf_pi.h \
    openssl/crypto/bio/bio_lcl.h \
    openssl/crypto/blake2/blake2_impl.h \
    openssl/crypto/blake2/blake2_locl.h \
    openssl/crypto/bn/bn_lcl.h \
    openssl/crypto/bn/bn_prime.h \
    openssl/crypto/bn/rsaz_exp.h \
    openssl/crypto/camellia/cmll_locl.h \
    openssl/crypto/cast/cast_lcl.h \
    openssl/crypto/cast/cast_s.h \
    openssl/crypto/cms/cms_lcl.h \
    openssl/crypto/comp/comp_lcl.h \
    openssl/crypto/conf/conf_def.h \
    openssl/crypto/conf/conf_lcl.h \
    openssl/crypto/crmf/crmf_int.h \
    openssl/crypto/ct/ct_locl.h \
    openssl/crypto/des/des_locl.h \
    openssl/crypto/des/spr.h \
    openssl/crypto/dh/dh_locl.h \
    openssl/crypto/dsa/dsa_locl.h \
    openssl/crypto/dso/dso_locl.h \
    openssl/crypto/ec/curve448/arch_32/arch_intrinsics.h \
    openssl/crypto/ec/curve448/arch_32/f_impl.h \
    openssl/crypto/ec/curve448/curve448_lcl.h \
    openssl/crypto/ec/curve448/curve448utils.h \
    openssl/crypto/ec/curve448/ed448.h \
    openssl/crypto/ec/curve448/field.h \
    openssl/crypto/ec/curve448/point_448.h \
    openssl/crypto/ec/curve448/word.h \
    openssl/crypto/ec/ec_lcl.h \
    openssl/crypto/engine/eng_int.h \
    openssl/crypto/evp/evp_locl.h \
    openssl/crypto/hmac/hmac_lcl.h \
    openssl/crypto/idea/idea_lcl.h \
    openssl/crypto/include/internal/aria.h \
    openssl/crypto/include/internal/asn1_int.h \
    openssl/crypto/include/internal/async.h \
    openssl/crypto/include/internal/bn_conf.h \
    openssl/crypto/include/internal/bn_dh.h \
    openssl/crypto/include/internal/bn_int.h \
    openssl/crypto/include/internal/bn_srp.h \
    openssl/crypto/include/internal/chacha.h \
    openssl/crypto/include/internal/cryptlib_int.h \
    openssl/crypto/include/internal/ctype.h \
    openssl/crypto/include/internal/dso_conf.h \
    openssl/crypto/include/internal/ec_int.h \
    openssl/crypto/include/internal/engine.h \
    openssl/crypto/include/internal/err_int.h \
    openssl/crypto/include/internal/ess_int.h \
    openssl/crypto/include/internal/evp_int.h \
    openssl/crypto/include/internal/lhash.h \
    openssl/crypto/include/internal/md32_common.h \
    openssl/crypto/include/internal/objects.h \
    openssl/crypto/include/internal/poly1305.h \
    openssl/crypto/include/internal/rand_int.h \
    openssl/crypto/include/internal/sha.h \
    openssl/crypto/include/internal/siphash.h \
    openssl/crypto/include/internal/sm2.h \
    openssl/crypto/include/internal/sm2err.h \
    openssl/crypto/include/internal/sm3.h \
    openssl/crypto/include/internal/sm4.h \
    openssl/crypto/include/internal/sparse_array.h \
    openssl/crypto/include/internal/store.h \
    openssl/crypto/include/internal/store_int.h \
    openssl/crypto/include/internal/x509_int.h \
    openssl/crypto/kdf/kdf_local.h \
    openssl/crypto/lhash/lhash_lcl.h \
    openssl/crypto/md4/md4_locl.h \
    openssl/crypto/md5/md5_locl.h \
    openssl/crypto/modes/modes_lcl.h \
    openssl/crypto/objects/obj_dat.h \
    openssl/crypto/objects/obj_lcl.h \
    openssl/crypto/objects/obj_xref.h \
    openssl/crypto/ocsp/ocsp_lcl.h \
    openssl/crypto/pkcs12/p12_lcl.h \
    openssl/crypto/poly1305/poly1305_local.h \
    openssl/crypto/property/property_lcl.h \
    openssl/crypto/rand/rand_lcl.h \
    openssl/crypto/rc2/rc2_locl.h \
    openssl/crypto/rc4/rc4_locl.h \
    openssl/crypto/rc5/rc5_locl.h \
    openssl/crypto/ripemd/rmd_locl.h \
    openssl/crypto/ripemd/rmdconst.h \
    openssl/crypto/rsa/rsa_locl.h \
    openssl/crypto/seed/seed_locl.h \
    openssl/crypto/sha/sha_locl.h \
    openssl/crypto/siphash/siphash_local.h \
    openssl/crypto/sm3/sm3_locl.h \
    openssl/crypto/store/store_locl.h \
    openssl/crypto/ts/ts_lcl.h \
    openssl/crypto/ui/ui_locl.h \
    openssl/crypto/whrlpool/wp_locl.h \
    openssl/crypto/x509/x509_lcl.h \
    openssl/crypto/x509v3/ext_dat.h \
    openssl/crypto/x509v3/pcy_int.h \
    openssl/crypto/x509v3/standard_exts.h \
    openssl/crypto/x509v3/v3_admis.h \
    openssl/crypto/arm_arch.h \
    openssl/crypto/buildinf.h \
    openssl/crypto/mips_arch.h \
    openssl/crypto/ppc_arch.h \
    openssl/crypto/provider_local.h \
    openssl/crypto/s390x_arch.h \
    openssl/crypto/sparc_arch.h \
    openssl/crypto/vms_rms.h \
    openssl/engines/e_afalg.h \
    openssl/engines/e_afalg_err.h \
    openssl/engines/e_capi_err.h \
    openssl/engines/e_dasync_err.h \
    openssl/engines/e_ossltest_err.h \
    openssl/include/internal/bio.h \
    openssl/include/internal/comp.h \
    openssl/include/internal/conf.h \
    openssl/include/internal/constant_time_locl.h \
    openssl/include/internal/core.h \
    openssl/include/internal/cryptlib.h \
    openssl/include/internal/dane.h \
    openssl/include/internal/dso.h \
    openssl/include/internal/dsoerr.h \
    openssl/include/internal/err.h \
    openssl/include/internal/ktls.h \
    openssl/include/internal/nelem.h \
    openssl/include/internal/numbers.h \
    openssl/include/internal/o_dir.h \
    openssl/include/internal/o_str.h \
    openssl/include/internal/property.h \
    openssl/include/internal/propertyerr.h \
    openssl/include/internal/provider.h \
    openssl/include/internal/refcount.h \
    openssl/include/internal/sockets.h \
    openssl/include/internal/sslconf.h \
    openssl/include/internal/symhacks.h \
    openssl/include/internal/thread_once.h \
    openssl/include/internal/tsan_assist.h \
    openssl/include/openssl/aes.h \
    openssl/include/openssl/asn1.h \
    openssl/include/openssl/asn1_mac.h \
    openssl/include/openssl/asn1err.h \
    openssl/include/openssl/asn1t.h \
    openssl/include/openssl/async.h \
    openssl/include/openssl/asyncerr.h \
    openssl/include/openssl/bio.h \
    openssl/include/openssl/bioerr.h \
    openssl/include/openssl/blowfish.h \
    openssl/include/openssl/bn.h \
    openssl/include/openssl/bnerr.h \
    openssl/include/openssl/buffer.h \
    openssl/include/openssl/buffererr.h \
    openssl/include/openssl/camellia.h \
    openssl/include/openssl/cast.h \
    openssl/include/openssl/cmac.h \
    openssl/include/openssl/cms.h \
    openssl/include/openssl/cmserr.h \
    openssl/include/openssl/comp.h \
    openssl/include/openssl/comperr.h \
    openssl/include/openssl/conf.h \
    openssl/include/openssl/conf_api.h \
    openssl/include/openssl/conferr.h \
    openssl/include/openssl/core.h \
    openssl/include/openssl/core_names.h \
    openssl/include/openssl/core_numbers.h \
    openssl/include/openssl/crmf.h \
    openssl/include/openssl/crmferr.h \
    openssl/include/openssl/crypto.h \
    openssl/include/openssl/cryptoerr.h \
    openssl/include/openssl/ct.h \
    openssl/include/openssl/cterr.h \
    openssl/include/openssl/des.h \
    openssl/include/openssl/dh.h \
    openssl/include/openssl/dherr.h \
    openssl/include/openssl/dsa.h \
    openssl/include/openssl/dsaerr.h \
    openssl/include/openssl/dtls1.h \
    openssl/include/openssl/e_os2.h \
    openssl/include/openssl/ebcdic.h \
    openssl/include/openssl/ec.h \
    openssl/include/openssl/ecdh.h \
    openssl/include/openssl/ecdsa.h \
    openssl/include/openssl/ecerr.h \
    openssl/include/openssl/engine.h \
    openssl/include/openssl/engineerr.h \
    openssl/include/openssl/err.h \
    openssl/include/openssl/ess.h \
    openssl/include/openssl/esserr.h \
    openssl/include/openssl/evp.h \
    openssl/include/openssl/evperr.h \
    openssl/include/openssl/hmac.h \
    openssl/include/openssl/idea.h \
    openssl/include/openssl/kdf.h \
    openssl/include/openssl/kdferr.h \
    openssl/include/openssl/lhash.h \
    openssl/include/openssl/md2.h \
    openssl/include/openssl/md4.h \
    openssl/include/openssl/md5.h \
    openssl/include/openssl/mdc2.h \
    openssl/include/openssl/modes.h \
    openssl/include/openssl/obj_mac.h \
    openssl/include/openssl/objects.h \
    openssl/include/openssl/objectserr.h \
    openssl/include/openssl/ocsp.h \
    openssl/include/openssl/ocsperr.h \
    openssl/include/openssl/opensslconf.h \
    openssl/include/openssl/opensslv.h \
    openssl/include/openssl/ossl_typ.h \
    openssl/include/openssl/params.h \
    openssl/include/openssl/pem.h \
    openssl/include/openssl/pem2.h \
    openssl/include/openssl/pemerr.h \
    openssl/include/openssl/pkcs12.h \
    openssl/include/openssl/pkcs12err.h \
    openssl/include/openssl/pkcs7.h \
    openssl/include/openssl/pkcs7err.h \
    openssl/include/openssl/provider.h \
    openssl/include/openssl/rand.h \
    openssl/include/openssl/rand_drbg.h \
    openssl/include/openssl/randerr.h \
    openssl/include/openssl/rc2.h \
    openssl/include/openssl/rc4.h \
    openssl/include/openssl/rc5.h \
    openssl/include/openssl/ripemd.h \
    openssl/include/openssl/rsa.h \
    openssl/include/openssl/rsaerr.h \
    openssl/include/openssl/safestack.h \
    openssl/include/openssl/seed.h \
    openssl/include/openssl/sha.h \
    openssl/include/openssl/srp.h \
    openssl/include/openssl/srtp.h \
    openssl/include/openssl/ssl.h \
    openssl/include/openssl/ssl2.h \
    openssl/include/openssl/ssl3.h \
    openssl/include/openssl/sslerr.h \
    openssl/include/openssl/stack.h \
    openssl/include/openssl/store.h \
    openssl/include/openssl/storeerr.h \
    openssl/include/openssl/symhacks.h \
    openssl/include/openssl/tls1.h \
    openssl/include/openssl/trace.h \
    openssl/include/openssl/ts.h \
    openssl/include/openssl/tserr.h \
    openssl/include/openssl/txt_db.h \
    openssl/include/openssl/ui.h \
    openssl/include/openssl/uierr.h \
    openssl/include/openssl/whrlpool.h \
    openssl/include/openssl/x509.h \
    openssl/include/openssl/x509_vfy.h \
    openssl/include/openssl/x509err.h \
    openssl/include/openssl/x509v3.h \
    openssl/include/openssl/x509v3err.h \
    openssl/ssl/record/record.h \
    openssl/ssl/record/record_locl.h \
    openssl/ssl/statem/statem.h \
    openssl/ssl/statem/statem_locl.h \
    openssl/ssl/packet_locl.h \
    openssl/ssl/ssl_cert_table.h \
    openssl/ssl/ssl_locl.h \
    openssl/e_os.h

SOURCES += \
    database.cpp \
    database_mongo_calculator.cpp \
    databasemongo.cpp \
    examRoutines.cpp \
    source_code_formatter.cpp \
    string_constants.cpp \
    test.cpp \
    vpf2Math3_SymmetricGroupsAndGeneralizations.cpp \
    vpf4CalculatorFunctionList.cpp \
    vpf5.cpp \
    vpf5_1CalculatorCode.cpp \
    vpf5_2javascript_graphics.cpp \
    vpf6.cpp \
    vpf6_05evaluationroutines.cpp \
    vpf6_0parsingRoutines.cpp \
    vpf6_1innerTypedFunctions.cpp \
    vpf6_2serialization_code.cpp \
    vpf6_35calculatorMathRoutinesPart2.cpp \
    vpf6_36calculatorHtmlRoutines.cpp \
    vpf6_37calculatorroutines.cpp \
    vpf6_38LaTeXRoutines.cpp \
    vpf6_3calculatorMathRoutines.cpp \
    vpf6_4ExpressionsImplementation.cpp \
    vpf7.cpp \
    vpf8.cpp \
    vpf9.cpp \
    vpf99_HardcodedData.cpp \
    vpf9_1.cpp \
    vpf9_2.cpp \
    vpf9_3RationalRadicals.cpp \
    vpf9_4SemisimpleLieAlgebras.cpp \
    vpf9_5SemisimpleLieAlgebras_RootSubalgebras.cpp \
    vpf9_6SemisimpleLieSubAlgebras.cpp \
    vpf9_7floating_point_routines.cpp \
    vpf9_85TimeDateWrappers.cpp \
    vpf9_8GlobalObjects.cpp \
    vpf9_92multitasking.cpp \
    vpf9_9SystemFunctions.cpp \
    vpfCharacters.cpp \
    vpfCharacters_CalculatorInterface.cpp \
    vpfCrypto.cpp \
    vpfCrypto_AES.cpp \
    vpfCrypto_ripemd.cpp \
    vpfCrypto_sha3.cpp \
    vpfEllipticCurves.cpp \
    vpfFiniteFields.cpp \
    vpfGraph.cpp \
    vpfHtmlInterpretationInterface.cpp \
    vpfHtmlSnippets.cpp \
    vpfJson.cpp \
    vpfWebServerInterProcessLogistics.cpp \
    web-routines-1.cpp \
    webserver.cpp \
    openssl/crypto/aes/aes_cbc.c \
    openssl/crypto/aes/aes_cfb.c \
    openssl/crypto/aes/aes_core.c \
    openssl/crypto/aes/aes_ecb.c \
    openssl/crypto/aes/aes_ige.c \
    openssl/crypto/aes/aes_misc.c \
    openssl/crypto/aes/aes_ofb.c \
    openssl/crypto/aes/aes_wrap.c \
    openssl/crypto/aria/aria.c \
    openssl/crypto/asn1/a_bitstr.c \
    openssl/crypto/asn1/a_d2i_fp.c \
    openssl/crypto/asn1/a_digest.c \
    openssl/crypto/asn1/a_dup.c \
    openssl/crypto/asn1/a_gentm.c \
    openssl/crypto/asn1/a_i2d_fp.c \
    openssl/crypto/asn1/a_int.c \
    openssl/crypto/asn1/a_mbstr.c \
    openssl/crypto/asn1/a_object.c \
    openssl/crypto/asn1/a_octet.c \
    openssl/crypto/asn1/a_print.c \
    openssl/crypto/asn1/a_sign.c \
    openssl/crypto/asn1/a_strex.c \
    openssl/crypto/asn1/a_strnid.c \
    openssl/crypto/asn1/a_time.c \
    openssl/crypto/asn1/a_type.c \
    openssl/crypto/asn1/a_utctm.c \
    openssl/crypto/asn1/a_utf8.c \
    openssl/crypto/asn1/a_verify.c \
    openssl/crypto/asn1/ameth_lib.c \
    openssl/crypto/asn1/asn1_err.c \
    openssl/crypto/asn1/asn1_gen.c \
    openssl/crypto/asn1/asn1_item_list.c \
    openssl/crypto/asn1/asn1_lib.c \
    openssl/crypto/asn1/asn1_par.c \
    openssl/crypto/asn1/asn_mime.c \
    openssl/crypto/asn1/asn_moid.c \
    openssl/crypto/asn1/asn_mstbl.c \
    openssl/crypto/asn1/asn_pack.c \
    openssl/crypto/asn1/bio_asn1.c \
    openssl/crypto/asn1/bio_ndef.c \
    openssl/crypto/asn1/d2i_pr.c \
    openssl/crypto/asn1/d2i_pu.c \
    openssl/crypto/asn1/evp_asn1.c \
    openssl/crypto/asn1/f_int.c \
    openssl/crypto/asn1/f_string.c \
    openssl/crypto/asn1/i2d_pr.c \
    openssl/crypto/asn1/i2d_pu.c \
    openssl/crypto/asn1/n_pkey.c \
    openssl/crypto/asn1/nsseq.c \
    openssl/crypto/asn1/p5_pbe.c \
    openssl/crypto/asn1/p5_pbev2.c \
    openssl/crypto/asn1/p5_scrypt.c \
    openssl/crypto/asn1/p8_pkey.c \
    openssl/crypto/asn1/t_bitst.c \
    openssl/crypto/asn1/t_pkey.c \
    openssl/crypto/asn1/t_spki.c \
    openssl/crypto/asn1/tasn_dec.c \
    openssl/crypto/asn1/tasn_enc.c \
    openssl/crypto/asn1/tasn_fre.c \
    openssl/crypto/asn1/tasn_new.c \
    openssl/crypto/asn1/tasn_prn.c \
    openssl/crypto/asn1/tasn_scn.c \
    openssl/crypto/asn1/tasn_typ.c \
    openssl/crypto/asn1/tasn_utl.c \
    openssl/crypto/asn1/x_algor.c \
    openssl/crypto/asn1/x_bignum.c \
    openssl/crypto/asn1/x_info.c \
    openssl/crypto/asn1/x_int64.c \
    openssl/crypto/asn1/x_long.c \
    openssl/crypto/asn1/x_pkey.c \
    openssl/crypto/asn1/x_sig.c \
    openssl/crypto/asn1/x_spki.c \
    openssl/crypto/asn1/x_val.c \
    openssl/crypto/async/arch/async_null.c \
    openssl/crypto/async/arch/async_posix.c \
    openssl/crypto/async/arch/async_win.c \
    openssl/crypto/async/async.c \
    openssl/crypto/async/async_err.c \
    openssl/crypto/async/async_wait.c \
    openssl/crypto/bf/bf_cfb64.c \
    openssl/crypto/bf/bf_ecb.c \
    openssl/crypto/bf/bf_enc.c \
    openssl/crypto/bf/bf_ofb64.c \
    openssl/crypto/bf/bf_skey.c \
    openssl/crypto/bio/b_addr.c \
    openssl/crypto/bio/b_dump.c \
    openssl/crypto/bio/b_print.c \
    openssl/crypto/bio/b_sock.c \
    openssl/crypto/bio/b_sock2.c \
    openssl/crypto/bio/bf_buff.c \
    openssl/crypto/bio/bf_lbuf.c \
    openssl/crypto/bio/bf_nbio.c \
    openssl/crypto/bio/bf_null.c \
    openssl/crypto/bio/bio_cb.c \
    openssl/crypto/bio/bio_err.c \
    openssl/crypto/bio/bio_lib.c \
    openssl/crypto/bio/bio_meth.c \
    openssl/crypto/bio/bss_acpt.c \
    openssl/crypto/bio/bss_bio.c \
    openssl/crypto/bio/bss_conn.c \
    openssl/crypto/bio/bss_fd.c \
    openssl/crypto/bio/bss_file.c \
    openssl/crypto/bio/bss_log.c \
    openssl/crypto/bio/bss_mem.c \
    openssl/crypto/bio/bss_null.c \
    openssl/crypto/bio/bss_sock.c \
    openssl/crypto/blake2/blake2b.c \
    openssl/crypto/blake2/blake2b_mac.c \
    openssl/crypto/blake2/blake2s.c \
    openssl/crypto/blake2/blake2s_mac.c \
    openssl/crypto/blake2/m_blake2b.c \
    openssl/crypto/blake2/m_blake2s.c \
    openssl/crypto/bn/bn_add.c \
    openssl/crypto/bn/bn_asm.c \
    openssl/crypto/bn/bn_blind.c \
    openssl/crypto/bn/bn_const.c \
    openssl/crypto/bn/bn_ctx.c \
    openssl/crypto/bn/bn_depr.c \
    openssl/crypto/bn/bn_dh.c \
    openssl/crypto/bn/bn_div.c \
    openssl/crypto/bn/bn_err.c \
    openssl/crypto/bn/bn_exp.c \
    openssl/crypto/bn/bn_exp2.c \
    openssl/crypto/bn/bn_gcd.c \
    openssl/crypto/bn/bn_gf2m.c \
    openssl/crypto/bn/bn_intern.c \
    openssl/crypto/bn/bn_kron.c \
    openssl/crypto/bn/bn_lib.c \
    openssl/crypto/bn/bn_mod.c \
    openssl/crypto/bn/bn_mont.c \
    openssl/crypto/bn/bn_mpi.c \
    openssl/crypto/bn/bn_mul.c \
    openssl/crypto/bn/bn_nist.c \
    openssl/crypto/bn/bn_prime.c \
    openssl/crypto/bn/bn_print.c \
    openssl/crypto/bn/bn_rand.c \
    openssl/crypto/bn/bn_recp.c \
    openssl/crypto/bn/bn_rsa_fips186_4.c \
    openssl/crypto/bn/bn_shift.c \
    openssl/crypto/bn/bn_sqr.c \
    openssl/crypto/bn/bn_sqrt.c \
    openssl/crypto/bn/bn_srp.c \
    openssl/crypto/bn/bn_word.c \
    openssl/crypto/bn/bn_x931p.c \
    openssl/crypto/bn/rsaz_exp.c \
    openssl/crypto/buffer/buf_err.c \
    openssl/crypto/buffer/buffer.c \
    openssl/crypto/camellia/camellia.c \
    openssl/crypto/camellia/cmll_cbc.c \
    openssl/crypto/camellia/cmll_cfb.c \
    openssl/crypto/camellia/cmll_ctr.c \
    openssl/crypto/camellia/cmll_ecb.c \
    openssl/crypto/camellia/cmll_misc.c \
    openssl/crypto/camellia/cmll_ofb.c \
    openssl/crypto/cast/c_cfb64.c \
    openssl/crypto/cast/c_ecb.c \
    openssl/crypto/cast/c_enc.c \
    openssl/crypto/cast/c_ofb64.c \
    openssl/crypto/cast/c_skey.c \
    openssl/crypto/chacha/chacha_enc.c \
    openssl/crypto/cmac/cm_ameth.c \
    openssl/crypto/cmac/cm_meth.c \
    openssl/crypto/cmac/cmac.c \
    openssl/crypto/cms/cms_asn1.c \
    openssl/crypto/cms/cms_att.c \
    openssl/crypto/cms/cms_cd.c \
    openssl/crypto/cms/cms_dd.c \
    openssl/crypto/cms/cms_enc.c \
    openssl/crypto/cms/cms_env.c \
    openssl/crypto/cms/cms_err.c \
    openssl/crypto/cms/cms_ess.c \
    openssl/crypto/cms/cms_io.c \
    openssl/crypto/cms/cms_kari.c \
    openssl/crypto/cms/cms_lib.c \
    openssl/crypto/cms/cms_pwri.c \
    openssl/crypto/cms/cms_sd.c \
    openssl/crypto/cms/cms_smime.c \
    openssl/crypto/comp/c_zlib.c \
    openssl/crypto/comp/comp_err.c \
    openssl/crypto/comp/comp_lib.c \
    openssl/crypto/conf/conf_api.c \
    openssl/crypto/conf/conf_def.c \
    openssl/crypto/conf/conf_err.c \
    openssl/crypto/conf/conf_lib.c \
    openssl/crypto/conf/conf_mall.c \
    openssl/crypto/conf/conf_mod.c \
    openssl/crypto/conf/conf_sap.c \
    openssl/crypto/conf/conf_ssl.c \
    openssl/crypto/crmf/crmf_asn.c \
    openssl/crypto/crmf/crmf_err.c \
    openssl/crypto/crmf/crmf_lib.c \
    openssl/crypto/crmf/crmf_pbm.c \
    openssl/crypto/ct/ct_b64.c \
    openssl/crypto/ct/ct_err.c \
    openssl/crypto/ct/ct_log.c \
    openssl/crypto/ct/ct_oct.c \
    openssl/crypto/ct/ct_policy.c \
    openssl/crypto/ct/ct_prn.c \
    openssl/crypto/ct/ct_sct.c \
    openssl/crypto/ct/ct_sct_ctx.c \
    openssl/crypto/ct/ct_vfy.c \
    openssl/crypto/ct/ct_x509v3.c \
    openssl/crypto/des/cbc_cksm.c \
    openssl/crypto/des/cfb64ede.c \
    openssl/crypto/des/cfb64enc.c \
    openssl/crypto/des/cfb_enc.c \
    openssl/crypto/des/des_enc.c \
    openssl/crypto/des/ecb3_enc.c \
    openssl/crypto/des/ecb_enc.c \
    openssl/crypto/des/fcrypt.c \
    openssl/crypto/des/fcrypt_b.c \
    openssl/crypto/des/ncbc_enc.c \
    openssl/crypto/des/ofb64ede.c \
    openssl/crypto/des/ofb64enc.c \
    openssl/crypto/des/ofb_enc.c \
    openssl/crypto/des/pcbc_enc.c \
    openssl/crypto/des/qud_cksm.c \
    openssl/crypto/des/rand_key.c \
    openssl/crypto/des/set_key.c \
    openssl/crypto/des/str2key.c \
    openssl/crypto/des/xcbc_enc.c \
    openssl/crypto/dh/dh_ameth.c \
    openssl/crypto/dh/dh_asn1.c \
    openssl/crypto/dh/dh_check.c \
    openssl/crypto/dh/dh_depr.c \
    openssl/crypto/dh/dh_err.c \
    openssl/crypto/dh/dh_gen.c \
    openssl/crypto/dh/dh_kdf.c \
    openssl/crypto/dh/dh_key.c \
    openssl/crypto/dh/dh_lib.c \
    openssl/crypto/dh/dh_meth.c \
    openssl/crypto/dh/dh_pmeth.c \
    openssl/crypto/dh/dh_prn.c \
    openssl/crypto/dh/dh_rfc5114.c \
    openssl/crypto/dh/dh_rfc7919.c \
    openssl/crypto/dsa/dsa_ameth.c \
    openssl/crypto/dsa/dsa_asn1.c \
    openssl/crypto/dsa/dsa_depr.c \
    openssl/crypto/dsa/dsa_err.c \
    openssl/crypto/dsa/dsa_gen.c \
    openssl/crypto/dsa/dsa_key.c \
    openssl/crypto/dsa/dsa_lib.c \
    openssl/crypto/dsa/dsa_meth.c \
    openssl/crypto/dsa/dsa_ossl.c \
    openssl/crypto/dsa/dsa_pmeth.c \
    openssl/crypto/dsa/dsa_prn.c \
    openssl/crypto/dsa/dsa_sign.c \
    openssl/crypto/dsa/dsa_vrf.c \
    openssl/crypto/dso/dso_dl.c \
    openssl/crypto/dso/dso_dlfcn.c \
    openssl/crypto/dso/dso_err.c \
    openssl/crypto/dso/dso_lib.c \
    openssl/crypto/dso/dso_openssl.c \
    openssl/crypto/dso/dso_vms.c \
    openssl/crypto/dso/dso_win32.c \
    openssl/crypto/ec/curve448/arch_32/f_impl.c \
    openssl/crypto/ec/curve448/curve448.c \
    openssl/crypto/ec/curve448/curve448_tables.c \
    openssl/crypto/ec/curve448/eddsa.c \
    openssl/crypto/ec/curve448/f_generic.c \
    openssl/crypto/ec/curve448/scalar.c \
    openssl/crypto/ec/curve25519.c \
    openssl/crypto/ec/ec2_oct.c \
    openssl/crypto/ec/ec2_smpl.c \
    openssl/crypto/ec/ec_ameth.c \
    openssl/crypto/ec/ec_asn1.c \
    openssl/crypto/ec/ec_check.c \
    openssl/crypto/ec/ec_curve.c \
    openssl/crypto/ec/ec_cvt.c \
    openssl/crypto/ec/ec_err.c \
    openssl/crypto/ec/ec_key.c \
    openssl/crypto/ec/ec_kmeth.c \
    openssl/crypto/ec/ec_lib.c \
    openssl/crypto/ec/ec_mult.c \
    openssl/crypto/ec/ec_oct.c \
    openssl/crypto/ec/ec_pmeth.c \
    openssl/crypto/ec/ec_print.c \
    openssl/crypto/ec/ecdh_kdf.c \
    openssl/crypto/ec/ecdh_ossl.c \
    openssl/crypto/ec/ecdsa_ossl.c \
    openssl/crypto/ec/ecdsa_sign.c \
    openssl/crypto/ec/ecdsa_vrf.c \
    openssl/crypto/ec/eck_prn.c \
    openssl/crypto/ec/ecp_mont.c \
    openssl/crypto/ec/ecp_nist.c \
    openssl/crypto/ec/ecp_nistp224.c \
    openssl/crypto/ec/ecp_nistp256.c \
    openssl/crypto/ec/ecp_nistp521.c \
    openssl/crypto/ec/ecp_nistputil.c \
    openssl/crypto/ec/ecp_nistz256_table.c \
    openssl/crypto/ec/ecp_oct.c \
    openssl/crypto/ec/ecp_smpl.c \
    openssl/crypto/ec/ecx_meth.c \
    openssl/crypto/engine/eng_all.c \
    openssl/crypto/engine/eng_cnf.c \
    openssl/crypto/engine/eng_ctrl.c \
    openssl/crypto/engine/eng_dyn.c \
    openssl/crypto/engine/eng_err.c \
    openssl/crypto/engine/eng_fat.c \
    openssl/crypto/engine/eng_init.c \
    openssl/crypto/engine/eng_lib.c \
    openssl/crypto/engine/eng_list.c \
    openssl/crypto/engine/eng_openssl.c \
    openssl/crypto/engine/eng_pkey.c \
    openssl/crypto/engine/eng_rdrand.c \
    openssl/crypto/engine/eng_table.c \
    openssl/crypto/engine/tb_asnmth.c \
    openssl/crypto/engine/tb_cipher.c \
    openssl/crypto/engine/tb_dh.c \
    openssl/crypto/engine/tb_digest.c \
    openssl/crypto/engine/tb_dsa.c \
    openssl/crypto/engine/tb_eckey.c \
    openssl/crypto/engine/tb_pkmeth.c \
    openssl/crypto/engine/tb_rand.c \
    openssl/crypto/engine/tb_rsa.c \
    openssl/crypto/err/err.c \
    openssl/crypto/err/err_all.c \
    openssl/crypto/err/err_prn.c \
    openssl/crypto/ess/ess_asn1.c \
    openssl/crypto/ess/ess_err.c \
    openssl/crypto/ess/ess_lib.c \
    openssl/crypto/evp/bio_b64.c \
    openssl/crypto/evp/bio_enc.c \
    openssl/crypto/evp/bio_md.c \
    openssl/crypto/evp/bio_ok.c \
    openssl/crypto/evp/c_allc.c \
    openssl/crypto/evp/c_alld.c \
    openssl/crypto/evp/c_allm.c \
    openssl/crypto/evp/cmeth_lib.c \
    openssl/crypto/evp/digest.c \
    openssl/crypto/evp/e_aes.c \
    openssl/crypto/evp/e_aes_cbc_hmac_sha1.c \
    openssl/crypto/evp/e_aes_cbc_hmac_sha256.c \
    openssl/crypto/evp/e_aria.c \
    openssl/crypto/evp/e_bf.c \
    openssl/crypto/evp/e_camellia.c \
    openssl/crypto/evp/e_cast.c \
    openssl/crypto/evp/e_chacha20_poly1305.c \
    openssl/crypto/evp/e_des.c \
    openssl/crypto/evp/e_des3.c \
    openssl/crypto/evp/e_idea.c \
    openssl/crypto/evp/e_null.c \
    openssl/crypto/evp/e_old.c \
    openssl/crypto/evp/e_rc2.c \
    openssl/crypto/evp/e_rc4.c \
    openssl/crypto/evp/e_rc4_hmac_md5.c \
    openssl/crypto/evp/e_rc5.c \
    openssl/crypto/evp/e_seed.c \
    openssl/crypto/evp/e_sm4.c \
    openssl/crypto/evp/e_xcbc_d.c \
    openssl/crypto/evp/encode.c \
    openssl/crypto/evp/evp_cnf.c \
    openssl/crypto/evp/evp_enc.c \
    openssl/crypto/evp/evp_err.c \
    openssl/crypto/evp/evp_fetch.c \
    openssl/crypto/evp/evp_key.c \
    openssl/crypto/evp/evp_lib.c \
    openssl/crypto/evp/evp_pbe.c \
    openssl/crypto/evp/evp_pkey.c \
    openssl/crypto/evp/kdf_lib.c \
    openssl/crypto/evp/m_md2.c \
    openssl/crypto/evp/m_md4.c \
    openssl/crypto/evp/m_md5.c \
    openssl/crypto/evp/m_md5_sha1.c \
    openssl/crypto/evp/m_mdc2.c \
    openssl/crypto/evp/m_null.c \
    openssl/crypto/evp/m_ripemd.c \
    openssl/crypto/evp/m_sha1.c \
    openssl/crypto/evp/m_sha3.c \
    openssl/crypto/evp/m_sigver.c \
    openssl/crypto/evp/m_wp.c \
    openssl/crypto/evp/mac_lib.c \
    openssl/crypto/evp/names.c \
    openssl/crypto/evp/p5_crpt.c \
    openssl/crypto/evp/p5_crpt2.c \
    openssl/crypto/evp/p_dec.c \
    openssl/crypto/evp/p_enc.c \
    openssl/crypto/evp/p_lib.c \
    openssl/crypto/evp/p_open.c \
    openssl/crypto/evp/p_seal.c \
    openssl/crypto/evp/p_sign.c \
    openssl/crypto/evp/p_verify.c \
    openssl/crypto/evp/pbe_scrypt.c \
    openssl/crypto/evp/pkey_kdf.c \
    openssl/crypto/evp/pkey_mac.c \
    openssl/crypto/evp/pmeth_fn.c \
    openssl/crypto/evp/pmeth_gn.c \
    openssl/crypto/evp/pmeth_lib.c \
    openssl/crypto/gmac/gmac.c \
    openssl/crypto/hmac/hm_ameth.c \
    openssl/crypto/hmac/hm_meth.c \
    openssl/crypto/hmac/hmac.c \
    openssl/crypto/idea/i_cbc.c \
    openssl/crypto/idea/i_cfb64.c \
    openssl/crypto/idea/i_ecb.c \
    openssl/crypto/idea/i_ofb64.c \
    openssl/crypto/idea/i_skey.c \
    openssl/crypto/kdf/hkdf.c \
    openssl/crypto/kdf/kdf_err.c \
    openssl/crypto/kdf/kdf_util.c \
    openssl/crypto/kdf/pbkdf2.c \
    openssl/crypto/kdf/scrypt.c \
    openssl/crypto/kdf/sshkdf.c \
    openssl/crypto/kdf/sskdf.c \
    openssl/crypto/kdf/tls1_prf.c \
    openssl/crypto/kmac/kmac.c \
    openssl/crypto/lhash/lh_stats.c \
    openssl/crypto/lhash/lhash.c \
    openssl/crypto/md2/md2_dgst.c \
    openssl/crypto/md2/md2_one.c \
    openssl/crypto/md4/md4_dgst.c \
    openssl/crypto/md4/md4_one.c \
    openssl/crypto/md5/md5_dgst.c \
    openssl/crypto/md5/md5_one.c \
    openssl/crypto/mdc2/mdc2_one.c \
    openssl/crypto/mdc2/mdc2dgst.c \
    openssl/crypto/modes/cbc128.c \
    openssl/crypto/modes/ccm128.c \
    openssl/crypto/modes/cfb128.c \
    openssl/crypto/modes/ctr128.c \
    openssl/crypto/modes/cts128.c \
    openssl/crypto/modes/gcm128.c \
    openssl/crypto/modes/ocb128.c \
    openssl/crypto/modes/ofb128.c \
    openssl/crypto/modes/siv128.c \
    openssl/crypto/modes/wrap128.c \
    openssl/crypto/modes/xts128.c \
    openssl/crypto/objects/o_names.c \
    openssl/crypto/objects/obj_dat.c \
    openssl/crypto/objects/obj_err.c \
    openssl/crypto/objects/obj_lib.c \
    openssl/crypto/objects/obj_xref.c \
    openssl/crypto/ocsp/ocsp_asn.c \
    openssl/crypto/ocsp/ocsp_cl.c \
    openssl/crypto/ocsp/ocsp_err.c \
    openssl/crypto/ocsp/ocsp_ext.c \
    openssl/crypto/ocsp/ocsp_ht.c \
    openssl/crypto/ocsp/ocsp_lib.c \
    openssl/crypto/ocsp/ocsp_prn.c \
    openssl/crypto/ocsp/ocsp_srv.c \
    openssl/crypto/ocsp/ocsp_vfy.c \
    openssl/crypto/ocsp/v3_ocsp.c \
    openssl/crypto/pem/pem_all.c \
    openssl/crypto/pem/pem_err.c \
    openssl/crypto/pem/pem_info.c \
    openssl/crypto/pem/pem_lib.c \
    openssl/crypto/pem/pem_oth.c \
    openssl/crypto/pem/pem_pk8.c \
    openssl/crypto/pem/pem_pkey.c \
    openssl/crypto/pem/pem_sign.c \
    openssl/crypto/pem/pem_x509.c \
    openssl/crypto/pem/pem_xaux.c \
    openssl/crypto/pem/pvkfmt.c \
    openssl/crypto/pkcs12/p12_add.c \
    openssl/crypto/pkcs12/p12_asn.c \
    openssl/crypto/pkcs12/p12_attr.c \
    openssl/crypto/pkcs12/p12_crpt.c \
    openssl/crypto/pkcs12/p12_crt.c \
    openssl/crypto/pkcs12/p12_decr.c \
    openssl/crypto/pkcs12/p12_init.c \
    openssl/crypto/pkcs12/p12_key.c \
    openssl/crypto/pkcs12/p12_kiss.c \
    openssl/crypto/pkcs12/p12_mutl.c \
    openssl/crypto/pkcs12/p12_npas.c \
    openssl/crypto/pkcs12/p12_p8d.c \
    openssl/crypto/pkcs12/p12_p8e.c \
    openssl/crypto/pkcs12/p12_sbag.c \
    openssl/crypto/pkcs12/p12_utl.c \
    openssl/crypto/pkcs12/pk12err.c \
    openssl/crypto/pkcs7/bio_pk7.c \
    openssl/crypto/pkcs7/pk7_asn1.c \
    openssl/crypto/pkcs7/pk7_attr.c \
    openssl/crypto/pkcs7/pk7_doit.c \
    openssl/crypto/pkcs7/pk7_lib.c \
    openssl/crypto/pkcs7/pk7_mime.c \
    openssl/crypto/pkcs7/pk7_smime.c \
    openssl/crypto/pkcs7/pkcs7err.c \
    openssl/crypto/poly1305/poly1305.c \
    openssl/crypto/poly1305/poly1305_ameth.c \
    openssl/crypto/poly1305/poly1305_base2_44.c \
    openssl/crypto/poly1305/poly1305_meth.c \
    openssl/crypto/property/defn_cache.c \
    openssl/crypto/property/property.c \
    openssl/crypto/property/property_err.c \
    openssl/crypto/property/property_parse.c \
    openssl/crypto/property/property_string.c \
    openssl/crypto/rand/drbg_ctr.c \
    openssl/crypto/rand/drbg_hash.c \
    openssl/crypto/rand/drbg_hmac.c \
    openssl/crypto/rand/drbg_lib.c \
    openssl/crypto/rand/rand_crng_test.c \
    openssl/crypto/rand/rand_egd.c \
    openssl/crypto/rand/rand_err.c \
    openssl/crypto/rand/rand_lib.c \
    openssl/crypto/rand/rand_unix.c \
    openssl/crypto/rand/rand_vms.c \
    openssl/crypto/rand/rand_win.c \
    openssl/crypto/rand/randfile.c \
    openssl/crypto/rc2/rc2_cbc.c \
    openssl/crypto/rc2/rc2_ecb.c \
    openssl/crypto/rc2/rc2_skey.c \
    openssl/crypto/rc2/rc2cfb64.c \
    openssl/crypto/rc2/rc2ofb64.c \
    openssl/crypto/rc4/rc4_enc.c \
    openssl/crypto/rc4/rc4_skey.c \
    openssl/crypto/rc5/rc5_ecb.c \
    openssl/crypto/rc5/rc5_enc.c \
    openssl/crypto/rc5/rc5_skey.c \
    openssl/crypto/rc5/rc5cfb64.c \
    openssl/crypto/rc5/rc5ofb64.c \
    openssl/crypto/ripemd/rmd_dgst.c \
    openssl/crypto/ripemd/rmd_one.c \
    openssl/crypto/rsa/rsa_ameth.c \
    openssl/crypto/rsa/rsa_asn1.c \
    openssl/crypto/rsa/rsa_chk.c \
    openssl/crypto/rsa/rsa_crpt.c \
    openssl/crypto/rsa/rsa_depr.c \
    openssl/crypto/rsa/rsa_err.c \
    openssl/crypto/rsa/rsa_gen.c \
    openssl/crypto/rsa/rsa_lib.c \
    openssl/crypto/rsa/rsa_meth.c \
    openssl/crypto/rsa/rsa_mp.c \
    openssl/crypto/rsa/rsa_none.c \
    openssl/crypto/rsa/rsa_oaep.c \
    openssl/crypto/rsa/rsa_ossl.c \
    openssl/crypto/rsa/rsa_pk1.c \
    openssl/crypto/rsa/rsa_pmeth.c \
    openssl/crypto/rsa/rsa_prn.c \
    openssl/crypto/rsa/rsa_pss.c \
    openssl/crypto/rsa/rsa_saos.c \
    openssl/crypto/rsa/rsa_sign.c \
    openssl/crypto/rsa/rsa_sp800_56b_check.c \
    openssl/crypto/rsa/rsa_sp800_56b_gen.c \
    openssl/crypto/rsa/rsa_ssl.c \
    openssl/crypto/rsa/rsa_x931.c \
    openssl/crypto/rsa/rsa_x931g.c \
    openssl/crypto/seed/seed.c \
    openssl/crypto/seed/seed_cbc.c \
    openssl/crypto/seed/seed_cfb.c \
    openssl/crypto/seed/seed_ecb.c \
    openssl/crypto/seed/seed_ofb.c \
    openssl/crypto/sha/keccak1600.c \
    openssl/crypto/sha/sha1_one.c \
    openssl/crypto/sha/sha1dgst.c \
    openssl/crypto/sha/sha256.c \
    openssl/crypto/sha/sha512.c \
    openssl/crypto/siphash/siphash.c \
    openssl/crypto/siphash/siphash_ameth.c \
    openssl/crypto/siphash/siphash_meth.c \
    openssl/crypto/sm2/sm2_crypt.c \
    openssl/crypto/sm2/sm2_err.c \
    openssl/crypto/sm2/sm2_pmeth.c \
    openssl/crypto/sm2/sm2_sign.c \
    openssl/crypto/sm3/m_sm3.c \
    openssl/crypto/sm3/sm3.c \
    openssl/crypto/sm4/sm4.c \
    openssl/crypto/srp/srp_lib.c \
    openssl/crypto/srp/srp_vfy.c \
    openssl/crypto/stack/stack.c \
    openssl/crypto/store/loader_file.c \
    openssl/crypto/store/store_err.c \
    openssl/crypto/store/store_init.c \
    openssl/crypto/store/store_lib.c \
    openssl/crypto/store/store_register.c \
    openssl/crypto/store/store_strings.c \
    openssl/crypto/ts/ts_asn1.c \
    openssl/crypto/ts/ts_conf.c \
    openssl/crypto/ts/ts_err.c \
    openssl/crypto/ts/ts_lib.c \
    openssl/crypto/ts/ts_req_print.c \
    openssl/crypto/ts/ts_req_utils.c \
    openssl/crypto/ts/ts_rsp_print.c \
    openssl/crypto/ts/ts_rsp_sign.c \
    openssl/crypto/ts/ts_rsp_utils.c \
    openssl/crypto/ts/ts_rsp_verify.c \
    openssl/crypto/ts/ts_verify_ctx.c \
    openssl/crypto/txt_db/txt_db.c \
    openssl/crypto/ui/ui_err.c \
    openssl/crypto/ui/ui_lib.c \
    openssl/crypto/ui/ui_null.c \
    openssl/crypto/ui/ui_openssl.c \
    openssl/crypto/ui/ui_util.c \
    openssl/crypto/whrlpool/wp_block.c \
    openssl/crypto/whrlpool/wp_dgst.c \
    openssl/crypto/x509/by_dir.c \
    openssl/crypto/x509/by_file.c \
    openssl/crypto/x509/t_crl.c \
    openssl/crypto/x509/t_req.c \
    openssl/crypto/x509/t_x509.c \
    openssl/crypto/x509/x509_att.c \
    openssl/crypto/x509/x509_cmp.c \
    openssl/crypto/x509/x509_d2.c \
    openssl/crypto/x509/x509_def.c \
    openssl/crypto/x509/x509_err.c \
    openssl/crypto/x509/x509_ext.c \
    openssl/crypto/x509/x509_lu.c \
    openssl/crypto/x509/x509_meth.c \
    openssl/crypto/x509/x509_obj.c \
    openssl/crypto/x509/x509_r2x.c \
    openssl/crypto/x509/x509_req.c \
    openssl/crypto/x509/x509_set.c \
    openssl/crypto/x509/x509_trs.c \
    openssl/crypto/x509/x509_txt.c \
    openssl/crypto/x509/x509_v3.c \
    openssl/crypto/x509/x509_vfy.c \
    openssl/crypto/x509/x509_vpm.c \
    openssl/crypto/x509/x509cset.c \
    openssl/crypto/x509/x509name.c \
    openssl/crypto/x509/x509rset.c \
    openssl/crypto/x509/x509spki.c \
    openssl/crypto/x509/x509type.c \
    openssl/crypto/x509/x_all.c \
    openssl/crypto/x509/x_attrib.c \
    openssl/crypto/x509/x_crl.c \
    openssl/crypto/x509/x_exten.c \
    openssl/crypto/x509/x_name.c \
    openssl/crypto/x509/x_pubkey.c \
    openssl/crypto/x509/x_req.c \
    openssl/crypto/x509/x_x509.c \
    openssl/crypto/x509/x_x509a.c \
    openssl/crypto/x509v3/pcy_cache.c \
    openssl/crypto/x509v3/pcy_data.c \
    openssl/crypto/x509v3/pcy_lib.c \
    openssl/crypto/x509v3/pcy_map.c \
    openssl/crypto/x509v3/pcy_node.c \
    openssl/crypto/x509v3/pcy_tree.c \
    openssl/crypto/x509v3/v3_addr.c \
    openssl/crypto/x509v3/v3_admis.c \
    openssl/crypto/x509v3/v3_akey.c \
    openssl/crypto/x509v3/v3_akeya.c \
    openssl/crypto/x509v3/v3_alt.c \
    openssl/crypto/x509v3/v3_asid.c \
    openssl/crypto/x509v3/v3_bcons.c \
    openssl/crypto/x509v3/v3_bitst.c \
    openssl/crypto/x509v3/v3_conf.c \
    openssl/crypto/x509v3/v3_cpols.c \
    openssl/crypto/x509v3/v3_crld.c \
    openssl/crypto/x509v3/v3_enum.c \
    openssl/crypto/x509v3/v3_extku.c \
    openssl/crypto/x509v3/v3_genn.c \
    openssl/crypto/x509v3/v3_ia5.c \
    openssl/crypto/x509v3/v3_info.c \
    openssl/crypto/x509v3/v3_int.c \
    openssl/crypto/x509v3/v3_lib.c \
    openssl/crypto/x509v3/v3_ncons.c \
    openssl/crypto/x509v3/v3_pci.c \
    openssl/crypto/x509v3/v3_pcia.c \
    openssl/crypto/x509v3/v3_pcons.c \
    openssl/crypto/x509v3/v3_pku.c \
    openssl/crypto/x509v3/v3_pmaps.c \
    openssl/crypto/x509v3/v3_prn.c \
    openssl/crypto/x509v3/v3_purp.c \
    openssl/crypto/x509v3/v3_skey.c \
    openssl/crypto/x509v3/v3_sxnet.c \
    openssl/crypto/x509v3/v3_tlsf.c \
    openssl/crypto/x509v3/v3_utl.c \
    openssl/crypto/x509v3/v3err.c \
    openssl/crypto/context.c \
    openssl/crypto/core_fetch.c \
    openssl/crypto/cpt_err.c \
    openssl/crypto/cryptlib.c \
    openssl/crypto/ctype.c \
    openssl/crypto/cversion.c \
    openssl/crypto/dllmain.c \
    openssl/crypto/ebcdic.c \
    openssl/crypto/ex_data.c \
    openssl/crypto/getenv.c \
    openssl/crypto/init.c \
    openssl/crypto/mem.c \
    openssl/crypto/mem_clr.c \
    openssl/crypto/mem_dbg.c \
    openssl/crypto/mem_sec.c \
    openssl/crypto/o_dir.c \
    openssl/crypto/o_fips.c \
    openssl/crypto/o_fopen.c \
    openssl/crypto/o_init.c \
    openssl/crypto/o_str.c \
    openssl/crypto/o_time.c \
    openssl/crypto/params.c \
    openssl/crypto/provider.c \
    openssl/crypto/provider_conf.c \
    openssl/crypto/provider_core.c \
    openssl/crypto/provider_predefined.c \
    openssl/crypto/sparse_array.c \
    openssl/crypto/threads_none.c \
    openssl/crypto/threads_pthread.c \
    openssl/crypto/threads_win.c \
    openssl/crypto/trace.c \
    openssl/crypto/uid.c \
    openssl/engines/e_capi.c \
    openssl/engines/e_capi_err.c \
    openssl/engines/e_dasync_err.c \
    openssl/ssl/record/dtls1_bitmap.c \
    openssl/ssl/record/rec_layer_d1.c \
    openssl/ssl/record/rec_layer_s3.c \
    openssl/ssl/record/ssl3_buffer.c \
    openssl/ssl/record/ssl3_record.c \
    openssl/ssl/record/ssl3_record_tls13.c \
    openssl/ssl/statem/extensions.c \
    openssl/ssl/statem/extensions_clnt.c \
    openssl/ssl/statem/extensions_cust.c \
    openssl/ssl/statem/extensions_srvr.c \
    openssl/ssl/statem/statem.c \
    openssl/ssl/statem/statem_clnt.c \
    openssl/ssl/statem/statem_dtls.c \
    openssl/ssl/statem/statem_lib.c \
    openssl/ssl/statem/statem_srvr.c \
    openssl/ssl/bio_ssl.c \
    openssl/ssl/d1_lib.c \
    openssl/ssl/d1_msg.c \
    openssl/ssl/d1_srtp.c \
    openssl/ssl/methods.c \
    openssl/ssl/packet.c \
    openssl/ssl/pqueue.c \
    openssl/ssl/s3_cbc.c \
    openssl/ssl/s3_enc.c \
    openssl/ssl/s3_lib.c \
    openssl/ssl/s3_msg.c \
    openssl/ssl/ssl_asn1.c \
    openssl/ssl/ssl_cert.c \
    openssl/ssl/ssl_ciph.c \
    openssl/ssl/ssl_conf.c \
    openssl/ssl/ssl_err.c \
    openssl/ssl/ssl_init.c \
    openssl/ssl/ssl_lib.c \
    openssl/ssl/ssl_mcnf.c \
    openssl/ssl/ssl_rsa.c \
    openssl/ssl/ssl_sess.c \
    openssl/ssl/ssl_stat.c \
    openssl/ssl/ssl_txt.c \
    openssl/ssl/ssl_utst.c \
    openssl/ssl/t1_enc.c \
    openssl/ssl/t1_lib.c \
    openssl/ssl/t1_trce.c \
    openssl/ssl/tls13_enc.c \
    openssl/ssl/tls_srp.c \
    openssl/crypto/LPdir_unix.c

